version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb_container
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false" 
volumes:
  mongo_data:
